package sk.upjs.ics.paz1c.gui;

import sk.upjs.ics.paz1c.entity.Student;

public class DetailStudentiFormular extends javax.swing.JFrame {

    public DetailStudentiFormular(Student student) {
        this();

        txtMeno.setText(student.getMeno());
        txtPriezvisko.setText(student.getPriezvisko());
        txtBydlisko.setText(student.getBydlisko());
        txtDatumNarodenia.setText(student.getDatumNarodenia().toString());
        txtKontakt.setText(student.getKontakt());
        txtPocetPokusov.setText(String.valueOf(student.getPocetPokusov()));
        txtPocetBodov.setText(String.valueOf(student.getPocetBodov()));

        if (student.isPrvaPomoc()) {
            txtPrvaPomoc.setText("ano");
        } else {
            txtPrvaPomoc.setText("nie");
        }

        if (student.isCvicisko()) {
            txtCvicisko.setText("ano");
        } else {
            txtCvicisko.setText("nie");
        }

        if (student.isJazda()) {
            txtJazda.setText("ano");
        } else {
            txtJazda.setText("nie");
        }
    }

    /**
     * Creates new form DetailStudentiFormular
     */
    private DetailStudentiFormular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMeno = new javax.swing.JLabel();
        lblPriezvisko = new javax.swing.JLabel();
        lblBydlisko = new javax.swing.JLabel();
        lblDatumNarodenia = new javax.swing.JLabel();
        lblKontakt = new javax.swing.JLabel();
        lblPocetBodov = new javax.swing.JLabel();
        lblPocetPokusov = new javax.swing.JLabel();
        lblPrvaPomoc = new javax.swing.JLabel();
        lblCvicisko = new javax.swing.JLabel();
        lblJazda = new javax.swing.JLabel();
        txtBydlisko = new javax.swing.JTextField();
        txtPriezvisko = new javax.swing.JTextField();
        txtPocetBodov = new javax.swing.JTextField();
        txtPocetPokusov = new javax.swing.JTextField();
        txtKontakt = new javax.swing.JTextField();
        txtMeno = new javax.swing.JTextField();
        txtCvicisko = new javax.swing.JTextField();
        txtPrvaPomoc = new javax.swing.JTextField();
        txtJazda = new javax.swing.JTextField();
        txtDatumNarodenia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student");
        setName("detailStudentiFrame"); // NOI18N
        setResizable(false);

        lblMeno.setText("Meno:");

        lblPriezvisko.setText("Priezvisko:");

        lblBydlisko.setText("Bydlisko:");

        lblDatumNarodenia.setText("Datum nar.:");

        lblKontakt.setText("Kontakt:");

        lblPocetBodov.setText("Pocet bodov:");

        lblPocetPokusov.setText("Pocet pokusov:");

        lblPrvaPomoc.setText("Prva pomoc:");

        lblCvicisko.setText("Cvicisko:");

        lblJazda.setText("Jazda:");

        txtBydlisko.setEditable(false);
        txtBydlisko.setFocusable(false);

        txtPriezvisko.setEditable(false);
        txtPriezvisko.setFocusable(false);

        txtPocetBodov.setEditable(false);
        txtPocetBodov.setFocusable(false);

        txtPocetPokusov.setEditable(false);
        txtPocetPokusov.setFocusable(false);

        txtKontakt.setEditable(false);
        txtKontakt.setFocusable(false);

        txtMeno.setEditable(false);
        txtMeno.setFocusable(false);

        txtCvicisko.setEditable(false);
        txtCvicisko.setFocusable(false);

        txtPrvaPomoc.setEditable(false);
        txtPrvaPomoc.setFocusable(false);

        txtJazda.setEditable(false);
        txtJazda.setFocusable(false);

        txtDatumNarodenia.setEditable(false);
        txtDatumNarodenia.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMeno)
                    .addComponent(lblPriezvisko)
                    .addComponent(lblBydlisko)
                    .addComponent(lblDatumNarodenia)
                    .addComponent(lblPrvaPomoc)
                    .addComponent(lblCvicisko)
                    .addComponent(lblKontakt)
                    .addComponent(lblPocetPokusov)
                    .addComponent(lblPocetBodov)
                    .addComponent(lblJazda))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDatumNarodenia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrvaPomoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCvicisko, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJazda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPocetBodov, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMeno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPocetPokusov, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPriezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBydlisko, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMeno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMeno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPriezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPriezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBydlisko, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBydlisko, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumNarodenia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatumNarodenia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPocetPokusov, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPocetPokusov, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPocetBodov, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPocetBodov, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrvaPomoc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrvaPomoc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCvicisko, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCvicisko, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJazda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJazda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailStudentiFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailStudentiFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailStudentiFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailStudentiFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailStudentiFormular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBydlisko;
    private javax.swing.JLabel lblCvicisko;
    private javax.swing.JLabel lblDatumNarodenia;
    private javax.swing.JLabel lblJazda;
    private javax.swing.JLabel lblKontakt;
    private javax.swing.JLabel lblMeno;
    private javax.swing.JLabel lblPocetBodov;
    private javax.swing.JLabel lblPocetPokusov;
    private javax.swing.JLabel lblPriezvisko;
    private javax.swing.JLabel lblPrvaPomoc;
    private javax.swing.JTextField txtBydlisko;
    private javax.swing.JTextField txtCvicisko;
    private javax.swing.JTextField txtDatumNarodenia;
    private javax.swing.JTextField txtJazda;
    private javax.swing.JTextField txtKontakt;
    private javax.swing.JTextField txtMeno;
    private javax.swing.JTextField txtPocetBodov;
    private javax.swing.JTextField txtPocetPokusov;
    private javax.swing.JTextField txtPriezvisko;
    private javax.swing.JTextField txtPrvaPomoc;
    // End of variables declaration//GEN-END:variables

}
