package sk.upjs.ics.paz1c.gui;

import java.sql.Date;
import java.sql.Time;
import java.util.List;
import sk.upjs.ics.paz1c.autoskola.BeanFactory;
import sk.upjs.ics.paz1c.dao.*;
import sk.upjs.ics.paz1c.entity.*;
import sk.upjs.ics.paz1c.gui.ComboBoxModels.*;

public class UpravaJazdyFormular extends javax.swing.JFrame {

    private JazdyDao jazdyDao = BeanFactory.INSTANCE.getJazdyDao();
    private StudentiDao studentiDao = BeanFactory.INSTANCE.getStudentiDao();
    private InstruktoriDao instruktoriDao = BeanFactory.INSTANCE.getInstruktoriDao();
    private VozidlaDao vozidlaDao = BeanFactory.INSTANCE.getVozidlaDao();

    private StudentComboBoxModel studentComboBoxModel = new StudentComboBoxModel();
    private InstruktorComboBoxModel instruktorComboBoxModel = new InstruktorComboBoxModel();
    private VozidloComboBoxModel vozidloComboBoxModel = new VozidloComboBoxModel();
    private DenComboBoxModel denComboBoxModel = new DenComboBoxModel();
    private MesiacComboBoxModel mesiacComboBoxModel = new MesiacComboBoxModel();
    private RokComboBoxModel rokComboBoxModel = new RokComboBoxModel();
    private HodinaComboBoxModel hodinaComboBoxModel = new HodinaComboBoxModel();
    private MinutaComboBoxModel minutaComboBoxModel = new MinutaComboBoxModel();

    private Jazda jazda;
    private HlavnyFormular rodic;

    public UpravaJazdyFormular(HlavnyFormular rodic, Jazda jazda) {
        this(jazda);
        this.rodic = rodic;
    }

    public UpravaJazdyFormular(Jazda jazda) {
        this();
        this.jazda = jazda;

        if (jazda.getId() != null) {
            pripravFormular();
        }
    }

    /**
     * Creates new form UpravaJazdyFormular
     */
    private UpravaJazdyFormular() {
        initComponents();
    }

    private void pripravFormular() {
        List<Student> studenti = studentiDao.dajVsetky();
        List<Instruktor> instruktori = instruktoriDao.dajVsetky();
        List<Vozidlo> vozidla = vozidlaDao.dajVsetky();
        int max = Math.max(Math.max(studenti.size(), instruktori.size()), vozidla.size());
        System.out.println(max + " a " + studenti.size());
        for (int i = 0; i < max; i++) {
            if (i < studenti.size() && jazda.getStudent().getId() == studenti.get(i).getId()) {
                cmBoxStudent.setSelectedIndex(i);
            }
            if (i < instruktori.size() && jazda.getInstruktor().getId() == instruktori.get(i).getId()) {
                cmBoxInstruktor.setSelectedIndex(i);
            }
            if (i < vozidla.size() && jazda.getVozidlo().getId() == vozidla.get(i).getId()) {
                cmBoxVozidlo.setSelectedIndex(i);
            }
        }

        cmBoxDen.setSelectedIndex(jazda.getDatum().getDate() - 1);
        cmBoxMesiac.setSelectedIndex(jazda.getDatum().getMonth());
        // + 1900 pretoze .getYear tolko odpocitava
        cmBoxRok.setSelectedIndex(jazda.getDatum().getYear() + 1900 - BeanFactory.INSTANCE.PRVY_ROK);
        cmBoxHodina.setSelectedIndex(jazda.getCas().getHours());
        cmBoxMinuta.setSelectedIndex(jazda.getCas().getMinutes());

        txtKm.setText(String.valueOf(jazda.getKm()));

        chBoxVpremavke.setSelected(jazda.isvPremavke());
        chBoxNacvicisku.setSelected(jazda.isNaCvicisku());
        chBoxSvozikom.setSelected(jazda.issVozikom());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudent = new javax.swing.JLabel();
        lblInstruktor = new javax.swing.JLabel();
        lblVozidlo = new javax.swing.JLabel();
        txtKm = new javax.swing.JTextField();
        lblDatum = new javax.swing.JLabel();
        lblCas = new javax.swing.JLabel();
        lblKm = new javax.swing.JLabel();
        chBoxVpremavke = new javax.swing.JCheckBox();
        chBoxNacvicisku = new javax.swing.JCheckBox();
        chBoxSvozikom = new javax.swing.JCheckBox();
        btnVynuluj = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        cmBoxDen = new javax.swing.JComboBox();
        cmBoxMesiac = new javax.swing.JComboBox();
        cmBoxRok = new javax.swing.JComboBox();
        cmBoxHodina = new javax.swing.JComboBox();
        cmBoxMinuta = new javax.swing.JComboBox();
        cmBoxStudent = new javax.swing.JComboBox();
        cmBoxInstruktor = new javax.swing.JComboBox();
        cmBoxVozidlo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jazda");
        setName("upravaJazdyFrame"); // NOI18N
        setResizable(false);

        lblStudent.setText("Student:");

        lblInstruktor.setText("Instruktor:");

        lblVozidlo.setText("Vozidlo:");

        lblDatum.setText("Datum:");

        lblCas.setText("Cas:");

        lblKm.setText("KM:");

        chBoxVpremavke.setText("V premavke");

        chBoxNacvicisku.setText("Na cvicisku");

        chBoxSvozikom.setText("S vozikom");

        btnVynuluj.setText("Vynuluj");
        btnVynuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVynulujActionPerformed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        cmBoxDen.setModel(denComboBoxModel);
        cmBoxDen.setSelectedIndex(0);

        cmBoxMesiac.setModel(mesiacComboBoxModel);
        cmBoxMesiac.setSelectedIndex(0);

        cmBoxRok.setModel(rokComboBoxModel);
        cmBoxRok.setSelectedIndex(0);

        cmBoxHodina.setModel(hodinaComboBoxModel);
        cmBoxHodina.setSelectedIndex(0);

        cmBoxMinuta.setModel(minutaComboBoxModel);
        cmBoxMinuta.setSelectedIndex(0);

        cmBoxStudent.setModel(studentComboBoxModel);
        cmBoxStudent.setSelectedIndex(0);

        cmBoxInstruktor.setModel(instruktorComboBoxModel);
        cmBoxInstruktor.setSelectedIndex(0);

        cmBoxVozidlo.setModel(vozidloComboBoxModel);
        cmBoxVozidlo.setSelectedIndex(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chBoxSvozikom)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(chBoxNacvicisku, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chBoxVpremavke, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblInstruktor)
                                .addComponent(lblVozidlo)
                                .addComponent(lblDatum)
                                .addComponent(lblCas)
                                .addComponent(lblKm)
                                .addComponent(lblStudent))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtKm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmBoxHodina, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmBoxMinuta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(cmBoxInstruktor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmBoxVozidlo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cmBoxDen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmBoxMesiac, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmBoxRok, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cmBoxStudent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnVynuluj, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmBoxStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmBoxInstruktor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInstruktor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmBoxVozidlo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVozidlo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmBoxDen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmBoxMesiac, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmBoxRok, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmBoxHodina, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmBoxMinuta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKm, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKm, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chBoxVpremavke, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chBoxNacvicisku, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chBoxSvozikom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVynuluj, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        jazda.setStudent((Student) cmBoxStudent.getSelectedItem());
        jazda.setInstruktor((Instruktor) cmBoxInstruktor.getSelectedItem());
        jazda.setVozidlo((Vozidlo) cmBoxVozidlo.getSelectedItem());

        StringBuilder datum = new StringBuilder();
        datum.append(cmBoxRok.getSelectedItem()).append("-")
                .append(cmBoxMesiac.getSelectedItem()).append("-")
                .append(cmBoxDen.getSelectedItem());
        jazda.setDatum(Date.valueOf(datum.toString()));
        StringBuilder cas = new StringBuilder();
        cas.append(cmBoxHodina.getSelectedItem()).append(":")
                .append(cmBoxMinuta.getSelectedItem()).append(":00");
        jazda.setCas(Time.valueOf(cas.toString()));

        jazda.setKm(Integer.valueOf(txtKm.getText()));

        jazda.setvPremavke(chBoxVpremavke.isSelected());
        jazda.setNaCvicisku(chBoxNacvicisku.isSelected());
        jazda.setsVozikom(chBoxSvozikom.isSelected());

        if (jazda.getId() == null) {
            jazdyDao.uloz(jazda);
        } else {
            jazdyDao.uprav(jazda);
        }

        if (rodic != null) {
            rodic.aktualizujZoznamJazd();
        }
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnVynulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVynulujActionPerformed
        cmBoxStudent.setSelectedIndex(0);
        cmBoxStudent.updateUI();
        cmBoxInstruktor.setSelectedIndex(0);
        cmBoxInstruktor.updateUI();
        cmBoxVozidlo.setSelectedIndex(0);
        cmBoxVozidlo.updateUI();

        cmBoxDen.setSelectedIndex(0);
        cmBoxDen.updateUI();
        cmBoxMesiac.setSelectedIndex(0);
        cmBoxMesiac.updateUI();
        cmBoxRok.setSelectedIndex(0);
        cmBoxRok.updateUI();

        cmBoxHodina.setSelectedIndex(0);
        cmBoxHodina.updateUI();
        cmBoxMinuta.setSelectedIndex(0);
        cmBoxMinuta.updateUI();

        txtKm.setText("");

        chBoxVpremavke.setSelected(false);
        chBoxNacvicisku.setSelected(false);
        chBoxSvozikom.setSelected(false);
    }//GEN-LAST:event_btnVynulujActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpravaJazdyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpravaJazdyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpravaJazdyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpravaJazdyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpravaJazdyFormular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnVynuluj;
    private javax.swing.JCheckBox chBoxNacvicisku;
    private javax.swing.JCheckBox chBoxSvozikom;
    private javax.swing.JCheckBox chBoxVpremavke;
    private javax.swing.JComboBox cmBoxDen;
    private javax.swing.JComboBox cmBoxHodina;
    private javax.swing.JComboBox cmBoxInstruktor;
    private javax.swing.JComboBox cmBoxMesiac;
    private javax.swing.JComboBox cmBoxMinuta;
    private javax.swing.JComboBox cmBoxRok;
    private javax.swing.JComboBox cmBoxStudent;
    private javax.swing.JComboBox cmBoxVozidlo;
    private javax.swing.JLabel lblCas;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblInstruktor;
    private javax.swing.JLabel lblKm;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JLabel lblVozidlo;
    private javax.swing.JTextField txtKm;
    // End of variables declaration//GEN-END:variables
}
