package sk.upjs.ics.paz1c.gui;

public class UpravaStudentiFormular extends javax.swing.JFrame {

    /** Creates new form UpravaStudentiFormular */
    public UpravaStudentiFormular() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMeno = new javax.swing.JLabel();
        lblPriezvisko = new javax.swing.JLabel();
        lblBydlisko = new javax.swing.JLabel();
        lblDatumNarodenia = new javax.swing.JLabel();
        lblKontakt = new javax.swing.JLabel();
        lblPvaPomoc = new javax.swing.JLabel();
        lblPocetBodov = new javax.swing.JLabel();
        lblPocetPokusov = new javax.swing.JLabel();
        lblCvicisko = new javax.swing.JLabel();
        lblJazda = new javax.swing.JLabel();
        txtPocetBodov = new javax.swing.JTextField();
        txtDatumNarodenia = new javax.swing.JTextField();
        txtPriezvisko = new javax.swing.JTextField();
        txtMeno = new javax.swing.JTextField();
        txtBydlisko = new javax.swing.JTextField();
        txtKontakt = new javax.swing.JTextField();
        txtPocetPokusov = new javax.swing.JTextField();
        rbtnPrvaPomocAno = new javax.swing.JRadioButton();
        rbtnPrvaPomocNie = new javax.swing.JRadioButton();
        rbtnCviciskoAno = new javax.swing.JRadioButton();
        rbtnCviciskoNie = new javax.swing.JRadioButton();
        rbtnJazdaAno = new javax.swing.JRadioButton();
        rbtnJazdaNie = new javax.swing.JRadioButton();
        btnOk = new javax.swing.JToggleButton();
        btnVynuluj = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student");
        setName("upravaStudentiFrame"); // NOI18N
        setResizable(false);

        lblMeno.setText("Meno:");

        lblPriezvisko.setText("Priezvisko:");

        lblBydlisko.setText("Bydlisko:");

        lblDatumNarodenia.setText("Datum nar.:");

        lblKontakt.setText("Kontakt:");

        lblPvaPomoc.setText("Prva pomoc:");

        lblPocetBodov.setText("Pocet bodov:");

        lblPocetPokusov.setText("Pocet pokusov:");

        lblCvicisko.setText("Cvicisko:");

        lblJazda.setText("Jazda:");

        rbtnPrvaPomocAno.setText("ano");

        rbtnPrvaPomocNie.setText("nie");

        rbtnCviciskoAno.setText("ano");

        rbtnCviciskoNie.setText("nie");

        rbtnJazdaAno.setText("ano");

        rbtnJazdaNie.setText("nie");

        btnOk.setText("OK");

        btnVynuluj.setText("Vynuluj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPocetBodov)
                    .addComponent(lblDatumNarodenia)
                    .addComponent(lblPriezvisko)
                    .addComponent(lblMeno)
                    .addComponent(lblBydlisko)
                    .addComponent(lblKontakt)
                    .addComponent(lblPocetPokusov)
                    .addComponent(lblPvaPomoc)
                    .addComponent(lblCvicisko)
                    .addComponent(lblJazda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnPrvaPomocAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnPrvaPomocNie))
                    .addComponent(txtPocetPokusov, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBydlisko, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMeno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPriezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumNarodenia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPocetBodov, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnCviciskoAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnCviciskoNie))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnJazdaAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnJazdaNie)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVynuluj, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMeno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMeno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPriezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPriezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBydlisko, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBydlisko, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumNarodenia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatumNarodenia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPocetPokusov, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPocetPokusov, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPocetBodov, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPocetBodov, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPvaPomoc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnPrvaPomocAno)
                    .addComponent(rbtnPrvaPomocNie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnCviciskoAno)
                    .addComponent(rbtnCviciskoNie)
                    .addComponent(lblCvicisko, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnJazdaAno)
                    .addComponent(rbtnJazdaNie)
                    .addComponent(lblJazda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVynuluj, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpravaStudentiFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpravaStudentiFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpravaStudentiFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpravaStudentiFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpravaStudentiFormular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnOk;
    private javax.swing.JToggleButton btnVynuluj;
    private javax.swing.JLabel lblBydlisko;
    private javax.swing.JLabel lblCvicisko;
    private javax.swing.JLabel lblDatumNarodenia;
    private javax.swing.JLabel lblJazda;
    private javax.swing.JLabel lblKontakt;
    private javax.swing.JLabel lblMeno;
    private javax.swing.JLabel lblPocetBodov;
    private javax.swing.JLabel lblPocetPokusov;
    private javax.swing.JLabel lblPriezvisko;
    private javax.swing.JLabel lblPvaPomoc;
    private javax.swing.JRadioButton rbtnCviciskoAno;
    private javax.swing.JRadioButton rbtnCviciskoNie;
    private javax.swing.JRadioButton rbtnJazdaAno;
    private javax.swing.JRadioButton rbtnJazdaNie;
    private javax.swing.JRadioButton rbtnPrvaPomocAno;
    private javax.swing.JRadioButton rbtnPrvaPomocNie;
    private javax.swing.JTextField txtBydlisko;
    private javax.swing.JTextField txtDatumNarodenia;
    private javax.swing.JTextField txtKontakt;
    private javax.swing.JTextField txtMeno;
    private javax.swing.JTextField txtPocetBodov;
    private javax.swing.JTextField txtPocetPokusov;
    private javax.swing.JTextField txtPriezvisko;
    // End of variables declaration//GEN-END:variables

}
