package sk.upjs.ics.paz1c.gui;

import java.sql.Date;
import java.sql.Time;
import java.util.ArrayList;
import java.util.List;
import sk.upjs.ics.paz1c.autoskola.BeanFactory;
import sk.upjs.ics.paz1c.dao.*;
import sk.upjs.ics.paz1c.entity.*;
import sk.upjs.ics.paz1c.gui.ComboBoxModels.*;

public class UpravaSkuskyFormular extends javax.swing.JFrame {

    private SkuskyDao skuskyDao = BeanFactory.INSTANCE.getSkuskyDao();
    private StudentiDao studentiDao = BeanFactory.INSTANCE.getStudentiDao();
    private InstruktoriDao instruktoriDao = BeanFactory.INSTANCE.getInstruktoriDao();

    private DenComboBoxModel denComboBoxModel = new DenComboBoxModel();
    private MesiacComboBoxModel mesiacComboBoxModel = new MesiacComboBoxModel();
    private RokComboBoxModel rokComboBoxModel = new RokComboBoxModel();
    private HodinaComboBoxModel hodinaComboBoxModel = new HodinaComboBoxModel();
    private MinutaComboBoxModel minutaComboBoxModel = new MinutaComboBoxModel();
    private InstruktorComboBoxModel instruktorComboBoxModel = new InstruktorComboBoxModel();
    private StudentComboBoxModel studentComboBoxModel = new StudentComboBoxModel();

    private Skuska skuska;
    private HlavnyFormular rodic;
    private List<Student> vybraniStudenti;

    public UpravaSkuskyFormular(HlavnyFormular rodic, Skuska skuska) {
        this(skuska);
        this.rodic = rodic;
    }

    public UpravaSkuskyFormular(Skuska skuska) {
        this();
        this.skuska = skuska;

        if (skuska.getId() != null) {
            pripravFormular();
        } else {
            vybraniStudenti = new ArrayList<>();
        }
    }

    /**
     * Creates new form UpravaSkuskyFormular
     */
    private UpravaSkuskyFormular() {
        initComponents();
    }

    private void pripravFormular() {
        cmBoxDen.setSelectedIndex(skuska.getDatum().getDate() - 1);
        cmBoxMesiac.setSelectedIndex(skuska.getDatum().getMonth());
        // + 1900 pretoze .getYear tolko odpocitava
        cmBoxRok.setSelectedIndex(skuska.getDatum().getYear() + 1900 - BeanFactory.INSTANCE.PRVY_ROK);
        cmBoxHodina.setSelectedIndex(skuska.getCas().getHours());
        cmBoxMinuta.setSelectedIndex(skuska.getCas().getMinutes());

        List<Instruktor> instruktori = instruktoriDao.dajVsetky();
        for (int i = 0; i < instruktori.size(); i++) {
            if (i < instruktori.size() && skuska.getInstruktor().getId() == instruktori.get(i).getId()) {
                cmBoxInstruktor.setSelectedIndex(i);
            }
        }

        vybraniStudenti = new ArrayList(skuska.getStudenti());
        lstStudenti.setListData(vybraniStudenti.toArray());

        txtPolicajt.setText(skuska.getPolicajt());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDatum = new javax.swing.JLabel();
        lblCas = new javax.swing.JLabel();
        lblInstruktor = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        lstStudenti = new javax.swing.JList();
        lblStudenti = new javax.swing.JLabel();
        txtPolicajt = new javax.swing.JTextField();
        lblPolicajt = new javax.swing.JLabel();
        btnVynuluj = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        cmBoxDen = new javax.swing.JComboBox();
        cmBoxMesiac = new javax.swing.JComboBox();
        cmBoxRok = new javax.swing.JComboBox();
        cmBoxHodina = new javax.swing.JComboBox();
        cmBoxMinuta = new javax.swing.JComboBox();
        cmBoxInstruktor = new javax.swing.JComboBox();
        cmBoxStudent = new javax.swing.JComboBox();
        btnPridaj = new javax.swing.JButton();
        btnVymaz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Skuska");
        setName("upravaSkuskyFrame"); // NOI18N
        setResizable(false);

        lblDatum.setText("Datum:");

        lblCas.setText("Cas:");

        lblInstruktor.setText("Instruktor:");

        scrollPane.setViewportView(lstStudenti);

        lblStudenti.setText("Studenti:");

        lblPolicajt.setText("Policajt:");

        btnVynuluj.setText("Vynuluj");
        btnVynuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVynulujActionPerformed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        cmBoxDen.setModel(denComboBoxModel);
        cmBoxDen.setSelectedIndex(0);

        cmBoxMesiac.setModel(mesiacComboBoxModel);
        cmBoxMesiac.setSelectedIndex(0);

        cmBoxRok.setModel(rokComboBoxModel);
        cmBoxRok.setSelectedIndex(0);

        cmBoxHodina.setModel(hodinaComboBoxModel);
        cmBoxHodina.setSelectedIndex(0);

        cmBoxMinuta.setModel(minutaComboBoxModel);
        cmBoxMinuta.setSelectedIndex(0);

        cmBoxInstruktor.setModel(instruktorComboBoxModel);
        cmBoxInstruktor.setSelectedIndex(0);

        cmBoxStudent.setModel(studentComboBoxModel);
        cmBoxStudent.setSelectedIndex(0);

        btnPridaj.setText("Pridaj");
        btnPridaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPridajActionPerformed(evt);
            }
        });

        btnVymaz.setText("Vymaz");
        btnVymaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVymazActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInstruktor)
                            .addComponent(lblDatum)
                            .addComponent(lblCas)
                            .addComponent(lblStudenti)
                            .addComponent(lblPolicajt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVynuluj, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmBoxDen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmBoxMesiac, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmBoxRok, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPolicajt)
                                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmBoxHodina, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmBoxMinuta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmBoxInstruktor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmBoxStudent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVymaz, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPridaj, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmBoxDen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmBoxMesiac, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmBoxRok, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmBoxHodina, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmBoxMinuta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstruktor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmBoxInstruktor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudenti, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmBoxStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPridaj, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVymaz, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPolicajt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPolicajt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVynuluj, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        StringBuilder datum = new StringBuilder();
        datum.append(cmBoxRok.getSelectedItem()).append("-")
                .append(cmBoxMesiac.getSelectedItem()).append("-")
                .append(cmBoxDen.getSelectedItem());
        skuska.setDatum(Date.valueOf(datum.toString()));
        StringBuilder cas = new StringBuilder();
        cas.append(cmBoxHodina.getSelectedItem()).append(":")
                .append(cmBoxMinuta.getSelectedItem()).append(":00");
        skuska.setCas(Time.valueOf(cas.toString()));

        skuska.setInstruktor((Instruktor) cmBoxInstruktor.getSelectedItem());
        skuska.setStudenti(new ArrayList<>(vybraniStudenti));
        skuska.setPolicajt(txtPolicajt.getText());

        if (skuska.getId() == null) {
            skuskyDao.uloz(skuska);
        } else {
            skuskyDao.uprav(skuska);
        }

        if (rodic != null) {
            rodic.aktualizujZoznamSkusok();
        }
        dispose();

    }//GEN-LAST:event_btnOkActionPerformed

    private void btnVynulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVynulujActionPerformed
        cmBoxDen.setSelectedIndex(0);
        cmBoxDen.updateUI();
        cmBoxMesiac.setSelectedIndex(0);
        cmBoxMesiac.updateUI();
        cmBoxRok.setSelectedIndex(0);
        cmBoxRok.updateUI();

        cmBoxHodina.setSelectedIndex(0);
        cmBoxHodina.updateUI();
        cmBoxMinuta.setSelectedIndex(0);
        cmBoxMinuta.updateUI();

        cmBoxInstruktor.setSelectedIndex(0);
        cmBoxInstruktor.updateUI();
        cmBoxStudent.setSelectedIndex(0);
        cmBoxStudent.updateUI();

        vybraniStudenti = new ArrayList<>();
        lstStudenti.setListData(vybraniStudenti.toArray());

        txtPolicajt.setText("");
    }//GEN-LAST:event_btnVynulujActionPerformed

    private void btnPridajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPridajActionPerformed
        Student student = (Student) cmBoxStudent.getSelectedItem();
        for (int i = 0; i < vybraniStudenti.size(); i++) {
            if (vybraniStudenti.get(i).getId() == student.getId()) {
                vybraniStudenti.remove(i);
                i--;
            }
        }
        vybraniStudenti.add(student);
        lstStudenti.setListData(vybraniStudenti.toArray());
    }//GEN-LAST:event_btnPridajActionPerformed

    private void btnVymazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVymazActionPerformed
        Student student = (Student) lstStudenti.getSelectedValue();
        vybraniStudenti.remove(student);
        lstStudenti.setListData(vybraniStudenti.toArray());
    }//GEN-LAST:event_btnVymazActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpravaSkuskyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpravaSkuskyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpravaSkuskyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpravaSkuskyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpravaSkuskyFormular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPridaj;
    private javax.swing.JButton btnVymaz;
    private javax.swing.JButton btnVynuluj;
    private javax.swing.JComboBox cmBoxDen;
    private javax.swing.JComboBox cmBoxHodina;
    private javax.swing.JComboBox cmBoxInstruktor;
    private javax.swing.JComboBox cmBoxMesiac;
    private javax.swing.JComboBox cmBoxMinuta;
    private javax.swing.JComboBox cmBoxRok;
    private javax.swing.JComboBox cmBoxStudent;
    private javax.swing.JLabel lblCas;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblInstruktor;
    private javax.swing.JLabel lblPolicajt;
    private javax.swing.JLabel lblStudenti;
    private javax.swing.JList lstStudenti;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField txtPolicajt;
    // End of variables declaration//GEN-END:variables

}
